version: "3.9" # Use the latest stable version if possible
name: kpi-demo

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  communication-control:
    image: 699475939717.dkr.ecr.eu-central-1.amazonaws.com/kpi-dev-ops-communication-controll
    container_name: com-control
    restart: always
    environment:
      Redis__ConnectionString: "redis:6379"
    ports:
      - "8080:8080"
    networks:
      - backend

  map-client:
    image: 699475939717.dkr.ecr.eu-central-1.amazonaws.com/kpi-dev-ops-map-client
    container_name: map-client
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - backend

networks:
  backend: