name: CodeQL Static Analysis

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze .NET and JS code
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Setup .NET (only for C#)
        if: matrix.language == 'csharp'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build .NET solution
        if: matrix.language == 'csharp'
        run: dotnet build src/CommunicationControl/DevOpsProject.sln --configuration Release

      - name: Install dependencies (only for JS)
        if: matrix.language == 'javascript'
        run: |
          cd src/MapClient
          npm ci

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3